# Generated by Django 3.2.6 on 2021-08-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bioskopi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioskop', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produkcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkcijske_kuce', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filmovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslovi', models.CharField(max_length=300)),
                ('zanrovi', models.CharField(max_length=100)),
                ('rezija', models.CharField(max_length=200)),
                ('glumci', models.CharField(max_length=300)),
                ('ocene', models.IntegerField()),
                ('biskis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmovi', to='filmovi.bioskopi')),
                ('produkcija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmovi', to='filmovi.produkcija')),
            ],
        ),
    ]
